const mongoose = require('mongoose');
const path = require('path');
require('dotenv').config({ path: path.resolve(__dirname, '../../.env') });

const connectDB = require('../config/db');
const { cloudinary } = require('../config/cloudinary');
const User = require('../models/User');
const Pet = require('../models/Pet');
const Report = require('../models/Report');
const SavedPet = require('../models/SavedPet');

/**
 * Upload remote image URL directly to Cloudinary as WebP format.
 */
const uploadToCloudinaryWebp = async (imageUrl, folder, publicIdHint) => {
    try {
        console.log(`  ☁ Uploading [${publicIdHint}] to Cloudinary...`);
        const result = await cloudinary.uploader.upload(imageUrl, {
            folder,
            public_id: publicIdHint,
            resource_type: 'image',
            format: 'webp',
            fetch_format: 'webp',
            quality: 'auto',
            overwrite: true,
            invalidate: true,
        });
        console.log(`  ✅ WebP Uploaded: ${result.secure_url}`);
        return {
            url: result.secure_url,
            publicId: result.public_id,
        };
    } catch (err) {
        console.warn(`  ⚠ Cloudinary upload warning (${err.message}). Using WebP URL.`);
        return {
            url: imageUrl.includes('unsplash') ? `${imageUrl}&fm=webp` : imageUrl,
            publicId: `fallback_${publicIdHint}`,
        };
    }
};

const seedData = async () => {
    try {
        console.log('🌱 Phase 1: Uploading Avatars & Pet Images to Cloudinary...');

        // ── 1. Upload Avatars ──
        const adminAvatar = await uploadToCloudinaryWebp('https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80', 'petaverse/avatars', 'admin_avatar');
        const priyaAvatar = await uploadToCloudinaryWebp('https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=400&q=80', 'petaverse/avatars', 'priya_avatar');
        const rahulAvatar = await uploadToCloudinaryWebp('https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80', 'petaverse/avatars', 'rahul_avatar');
        const ananyaAvatar = await uploadToCloudinaryWebp('https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=400&q=80', 'petaverse/avatars', 'ananya_avatar');
        const rajAvatar = await uploadToCloudinaryWebp('https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80', 'petaverse/avatars', 'raj_avatar');

        // ── 2. Upload Pet Images ──
        // 🐶 DOGS (5)
        const dog1 = await uploadToCloudinaryWebp('https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=800&q=80', 'petaverse/pets', 'dog_bella');
        const dog2 = await uploadToCloudinaryWebp('https://images.unsplash.com/photo-1589941013453-ec89f33b5e95?auto=format&fit=crop&w=800&q=80', 'petaverse/pets', 'dog_max');
        const dog3 = await uploadToCloudinaryWebp('https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&w=800&q=80', 'petaverse/pets', 'dog_rocky');
        const dog4 = await uploadToCloudinaryWebp('https://images.unsplash.com/photo-1537151608828-ea2b11777ee8?auto=format&fit=crop&w=800&q=80', 'petaverse/pets', 'dog_cooper');
        const dog5 = await uploadToCloudinaryWebp('https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&w=800&q=80', 'petaverse/pets', 'dog_daisy');

        // 🐱 CATS (5)
        const cat1 = await uploadToCloudinaryWebp('https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&w=800&q=80', 'petaverse/pets', 'cat_luna');
        const cat2 = await uploadToCloudinaryWebp('https://images.unsplash.com/photo-1513360371669-4adf3dd7dff8?auto=format&fit=crop&w=800&q=80', 'petaverse/pets', 'cat_milo');
        const cat3 = await uploadToCloudinaryWebp('https://images.unsplash.com/photo-1573865526739-10659fec78a5?auto=format&fit=crop&w=800&q=80', 'petaverse/pets', 'cat_oliver');
        const cat4 = await uploadToCloudinaryWebp('https://images.unsplash.com/photo-1533738363-b7f9aef128ce?auto=format&fit=crop&w=800&q=80', 'petaverse/pets', 'cat_simba');
        const cat5 = await uploadToCloudinaryWebp('https://images.unsplash.com/photo-1548802673-380ab8ebc7b7?auto=format&fit=crop&w=800&q=80', 'petaverse/pets', 'cat_chloe');

        // 🦜 BIRDS (5)
        const bird1 = await uploadToCloudinaryWebp('https://images.unsplash.com/photo-1552728089-57bdde30beb3?auto=format&fit=crop&w=800&q=80', 'petaverse/pets', 'bird_rio');
        const bird2 = await uploadToCloudinaryWebp('https://images.unsplash.com/photo-1522858547137-f1dcec554f55?auto=format&fit=crop&w=800&q=80', 'petaverse/pets', 'bird_kiwi');
        const bird3 = await uploadToCloudinaryWebp('https://images.unsplash.com/photo-1591567396934-2e6730999086?auto=format&fit=crop&w=800&q=80', 'petaverse/pets', 'bird_sunny');
        const bird4 = await uploadToCloudinaryWebp('https://images.unsplash.com/photo-1606567595334-d39972c85dbe?auto=format&fit=crop&w=800&q=80', 'petaverse/pets', 'bird_charlie');
        const bird5 = await uploadToCloudinaryWebp('https://images.unsplash.com/photo-1452570053594-1b985d6ea890?auto=format&fit=crop&w=800&q=80', 'petaverse/pets', 'bird_peaches');

        // 🐠 FISH (5)
        const fish1 = await uploadToCloudinaryWebp('https://images.unsplash.com/photo-1522069169874-c58ec4b76be5?auto=format&fit=crop&w=800&q=80', 'petaverse/pets', 'fish_goldie');
        const fish2 = await uploadToCloudinaryWebp('https://images.unsplash.com/photo-1535591273668-578e31182c4f?auto=format&fit=crop&w=800&q=80', 'petaverse/pets', 'fish_bluey');
        const fish3 = await uploadToCloudinaryWebp('https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=800&q=80', 'petaverse/pets', 'fish_nemo');
        const fish4 = await uploadToCloudinaryWebp('https://images.unsplash.com/photo-1520315343548-c9fbff67b579?auto=format&fit=crop&w=800&q=80', 'petaverse/pets', 'fish_discus');
        const fish5 = await uploadToCloudinaryWebp('https://images.unsplash.com/photo-1524704654690-b56c05c78a00?auto=format&fit=crop&w=800&q=80', 'petaverse/pets', 'fish_angel');

        // 🐰 RABBITS (5)
        const rabbit1 = await uploadToCloudinaryWebp('https://images.unsplash.com/photo-1585110396000-c9ffd4e4b308?auto=format&fit=crop&w=800&q=80', 'petaverse/pets', 'rabbit_coco');
        const rabbit2 = await uploadToCloudinaryWebp('https://images.unsplash.com/photo-1591382386627-349b692688ff?auto=format&fit=crop&w=800&q=80', 'petaverse/pets', 'rabbit_snowball');
        const rabbit3 = await uploadToCloudinaryWebp('https://images.unsplash.com/photo-1535241749838-299277b6305f?auto=format&fit=crop&w=800&q=80', 'petaverse/pets', 'rabbit_bunbun');
        const rabbit4 = await uploadToCloudinaryWebp('https://images.unsplash.com/photo-1583301286816-f4f05e1e8b25?auto=format&fit=crop&w=800&q=80', 'petaverse/pets', 'rabbit_oreo');
        const rabbit5 = await uploadToCloudinaryWebp('https://images.unsplash.com/photo-1559214362-e6d1dce4f917?auto=format&fit=crop&w=800&q=80', 'petaverse/pets', 'rabbit_hazel');

        // 🐹 HAMSTERS (5 - Owned by Raj Dubey)
        const hamster1 = await uploadToCloudinaryWebp('https://images.unsplash.com/photo-1425082661705-1834bfd09dca?auto=format&fit=crop&w=800&q=80', 'petaverse/pets', 'hamster_peanut');
        const hamster2 = await uploadToCloudinaryWebp('https://images.unsplash.com/photo-1548767797-d8c844163c4c?auto=format&fit=crop&w=800&q=80', 'petaverse/pets', 'hamster_nibbles');
        const hamster3 = await uploadToCloudinaryWebp('https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=800&q=80', 'petaverse/pets', 'hamster_cheeks');
        const hamster4 = await uploadToCloudinaryWebp('https://images.unsplash.com/photo-1508455858334-95337ba25607?auto=format&fit=crop&w=800&q=80', 'petaverse/pets', 'hamster_mochi');
        const hamster5 = await uploadToCloudinaryWebp('https://images.unsplash.com/photo-1563460716037-460a3ad24ba9?auto=format&fit=crop&w=800&q=80', 'petaverse/pets', 'hamster_pippin');

        // 🦎 REPTILES (5 - Owned by Raj Dubey)
        const reptile1 = await uploadToCloudinaryWebp('https://images.unsplash.com/photo-1563460716037-460a3ad24ba9?auto=format&fit=crop&w=800&q=80', 'petaverse/pets', 'reptile_spike');
        const reptile2 = await uploadToCloudinaryWebp('https://images.unsplash.com/photo-1508455858334-95337ba25607?auto=format&fit=crop&w=800&q=80', 'petaverse/pets', 'reptile_ziggy');
        const reptile3 = await uploadToCloudinaryWebp('https://images.unsplash.com/photo-1518791841217-8f162f1e1131?auto=format&fit=crop&w=800&q=80', 'petaverse/pets', 'reptile_shelly');
        const reptile4 = await uploadToCloudinaryWebp('https://images.unsplash.com/photo-1560807707-8cc77767d783?auto=format&fit=crop&w=800&q=80', 'petaverse/pets', 'reptile_draco');
        const reptile5 = await uploadToCloudinaryWebp('https://images.unsplash.com/photo-1531386151447-fd76ad50012f?auto=format&fit=crop&w=800&q=80', 'petaverse/pets', 'reptile_kaa');

        // 🐾 OTHER PETS (5)
        const other1 = await uploadToCloudinaryWebp('https://images.unsplash.com/photo-1548767797-d8c844163c4c?auto=format&fit=crop&w=800&q=80', 'petaverse/pets', 'other_gizmo');
        const other2 = await uploadToCloudinaryWebp('https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=800&q=80', 'petaverse/pets', 'other_bandit');
        const other3 = await uploadToCloudinaryWebp('https://images.unsplash.com/photo-1425082661705-1834bfd09dca?auto=format&fit=crop&w=800&q=80', 'petaverse/pets', 'other_charlie');
        const other4 = await uploadToCloudinaryWebp('https://images.unsplash.com/photo-1508455858334-95337ba25607?auto=format&fit=crop&w=800&q=80', 'petaverse/pets', 'other_sammy');
        const other5 = await uploadToCloudinaryWebp('https://images.unsplash.com/photo-1563460716037-460a3ad24ba9?auto=format&fit=crop&w=800&q=80', 'petaverse/pets', 'other_rusty');

        console.log('✅ Phase 1 Complete: All Cloudinary Images Uploaded.');

        // ── Phase 2: Connect to MongoDB & Insert Data ──
        console.log('🌱 Phase 2: Connecting to MongoDB Atlas & Inserting Documents...');
        await connectDB();

        console.log('🧹 Clearing existing collections...');
        await Promise.all([
            User.deleteMany({}),
            Pet.deleteMany({}),
            Report.deleteMany({}),
            SavedPet.deleteMany({}),
        ]);
        console.log('✅ Collections cleared.');

        const users = await User.create([
            {
                googleId: 'google_admin_1001',
                email: 'admin@petaverse.com',
                password: 'Password123!',
                name: 'Admin PetVerse',
                role: 'admin',
                bio: 'Official Admin Account for PetVerse Platform',
                location: { city: 'New Delhi', state: 'Delhi', country: 'India' },
                phone: '+919876543210',
                avatar: adminAvatar,
            },
            {
                googleId: 'google_user_1002',
                email: 'divya02@gmail.com',
                password: 'Password123!',
                name: 'Priya Sharma',
                role: 'user',
                bio: 'Passionate dog lover and animal welfare volunteer.',
                location: { city: 'Delhi', state: 'Delhi', country: 'India' },
                phone: '+919812345678',
                avatar: priyaAvatar,
            },
            {
                googleId: 'google_user_1003',
                email: 'rahul.verma@example.com',
                password: 'Password123!',
                name: 'Rahul Verma',
                role: 'user',
                bio: 'Cat parent and advocate for stray animal care.',
                location: { city: 'Mumbai', state: 'Maharashtra', country: 'India' },
                phone: '+919898765432',
                avatar: rahulAvatar,
            },
            {
                googleId: 'google_user_1004',
                email: 'ananya.patel@example.com',
                password: 'Password123!',
                name: 'Ananya Patel',
                role: 'user',
                bio: 'Pet enthusiast interested in adoption & rehoming.',
                location: { city: 'Bengaluru', state: 'Karnataka', country: 'India' },
                phone: '+919765432109',
                avatar: ananyaAvatar,
            },
            {
                googleId: 'google_user_1005',
                email: 'raj.dubey@example.com',
                password: 'Password123!',
                name: 'Raj Dubey',
                role: 'user',
                bio: 'Exotic pet enthusiast, hamster care advocate, and reptile breeder.',
                location: { city: 'Noida', state: 'Uttar Pradesh', country: 'India' },
                phone: '+919988776655',
                avatar: rajAvatar,
            },
        ]);
        console.log(`✅ ${users.length} Users created in MongoDB.`);

        const [adminUser, priya, rahul, ananya, raj] = users;

        const petsData = [
            // ── 🐶 DOGS (5) ──
            {
                owner: priya._id,
                name: 'Bella',
                species: 'dog',
                breed: 'Golden Retriever',
                age: { value: 2, unit: 'years' },
                gender: 'female',
                size: 'large',
                color: 'Golden',
                description: 'Friendly, energetic Golden Retriever looking for a loving home. Loves playing fetch and is great with kids!',
                healthStatus: { vaccinated: true, neutered: true, microchipped: true, notes: 'Fully vaccinated & healthy.' },
                listingType: 'adoption',
                status: 'available',
                price: 0,
                location: { city: 'Delhi', state: 'Delhi', country: 'India' },
                images: [{ ...dog1, isPrimary: true }],
                tags: ['Friendly', 'Trained', 'Playful'],
                contactInfo: { phone: '+919812345678', email: 'priya.sharma@example.com', preferredMethod: 'phone' },
                isFeatured: true,
                isVerified: true,
                viewCount: 154,
            },
            {
                owner: ananya._id,
                name: 'Max',
                species: 'dog',
                breed: 'German Shepherd',
                age: { value: 3, unit: 'years' },
                gender: 'male',
                size: 'large',
                color: 'Black & Tan',
                description: 'Loyal and highly intelligent German Shepherd. Active family needed.',
                healthStatus: { vaccinated: true, neutered: true, microchipped: true, notes: 'Guard training completed.' },
                listingType: 'rehoming',
                status: 'available',
                price: 0,
                location: { city: 'Bengaluru', state: 'Karnataka', country: 'India' },
                images: [{ ...dog2, isPrimary: true }],
                tags: ['Guard Dog', 'Trained', 'Active'],
                contactInfo: { phone: '+919765432109', email: 'ananya.patel@example.com', preferredMethod: 'email' },
                isFeatured: true,
                isVerified: true,
                viewCount: 220,
            },
            {
                owner: rahul._id,
                name: 'Rocky',
                species: 'dog',
                breed: 'Labrador Retriever',
                age: { value: 4, unit: 'years' },
                gender: 'male',
                size: 'large',
                color: 'Chocolate Brown',
                description: 'LOST PET: Rocky went missing near Bandra West. Red collar with name tag.',
                healthStatus: { vaccinated: true, neutered: true, microchipped: true, notes: 'Microchip ID #9820001234' },
                listingType: 'lost',
                status: 'available',
                price: 0,
                location: { city: 'Mumbai', state: 'Maharashtra', country: 'India' },
                images: [{ ...dog3, isPrimary: true }],
                tags: ['Lost Pet', 'Reward Offered', 'Labrador'],
                contactInfo: { phone: '+919898765432', email: 'rahul.verma@example.com', preferredMethod: 'phone' },
                isFeatured: false,
                isVerified: true,
                viewCount: 310,
            },
            {
                owner: priya._id,
                name: 'Cooper',
                species: 'dog',
                breed: 'Beagle',
                age: { value: 1, unit: 'years' },
                gender: 'male',
                size: 'medium',
                color: 'Tricolor',
                description: 'Playful Beagle puppy with high energy and affectionate nature.',
                healthStatus: { vaccinated: true, neutered: false, microchipped: false, notes: 'Dewormed and vaccinated.' },
                listingType: 'sale',
                status: 'available',
                price: 12000,
                location: { city: 'Pune', state: 'Maharashtra', country: 'India' },
                images: [{ ...dog4, isPrimary: true }],
                tags: ['Puppy', 'Energetic', 'Beagle'],
                contactInfo: { phone: '+919812345678', email: 'priya.sharma@example.com', preferredMethod: 'phone' },
                isFeatured: false,
                isVerified: true,
                viewCount: 95,
            },
            {
                owner: rahul._id,
                name: 'Daisy',
                species: 'dog',
                breed: 'Shih Tzu',
                age: { value: 6, unit: 'months' },
                gender: 'female',
                size: 'small',
                color: 'White & Brown',
                description: 'Cute Shih Tzu puppy available for adoption to a loving home.',
                healthStatus: { vaccinated: true, neutered: false, microchipped: false, notes: 'First vet checkup done.' },
                listingType: 'adoption',
                status: 'available',
                price: 0,
                location: { city: 'Chandigarh', state: 'Punjab', country: 'India' },
                images: [{ ...dog5, isPrimary: true }],
                tags: ['Small Breed', 'Cute', 'Lap Dog'],
                contactInfo: { phone: '+919898765432', email: 'rahul.verma@example.com', preferredMethod: 'platform' },
                isFeatured: false,
                isVerified: true,
                viewCount: 112,
            },

            // ── 🐱 CATS (5) ──
            {
                owner: rahul._id,
                name: 'Luna',
                species: 'cat',
                breed: 'Persian',
                age: { value: 1, unit: 'years' },
                gender: 'female',
                size: 'small',
                color: 'White',
                description: 'Gentle Persian cat. Loves quiet environments and sunny cuddles.',
                healthStatus: { vaccinated: true, neutered: true, microchipped: false, notes: 'Fully vaccinated.' },
                listingType: 'adoption',
                status: 'available',
                price: 0,
                location: { city: 'Mumbai', state: 'Maharashtra', country: 'India' },
                images: [{ ...cat1, isPrimary: true }],
                tags: ['Calm', 'Indoor', 'Fluffy'],
                contactInfo: { phone: '+919898765432', email: 'rahul.verma@example.com', preferredMethod: 'platform' },
                isFeatured: true,
                isVerified: true,
                viewCount: 130,
            },
            {
                owner: priya._id,
                name: 'Milo',
                species: 'cat',
                breed: 'Siamese',
                age: { value: 6, unit: 'months' },
                gender: 'male',
                size: 'small',
                color: 'Cream & Dark Brown',
                description: 'Vocal, playful Siamese kitten with stunning blue eyes.',
                healthStatus: { vaccinated: true, neutered: false, microchipped: false, notes: 'Vaccinated.' },
                listingType: 'sale',
                status: 'available',
                price: 8500,
                location: { city: 'Delhi', state: 'Delhi', country: 'India' },
                images: [{ ...cat2, isPrimary: true }],
                tags: ['Siamese', 'Blue Eyes', 'Playful'],
                contactInfo: { phone: '+919812345678', email: 'priya.sharma@example.com', preferredMethod: 'phone' },
                isFeatured: false,
                isVerified: true,
                viewCount: 88,
            },
            {
                owner: ananya._id,
                name: 'Oliver',
                species: 'cat',
                breed: 'British Shorthair',
                age: { value: 2, unit: 'years' },
                gender: 'male',
                size: 'medium',
                color: 'Grey',
                description: 'Handsome British Shorthair cat looking for a caring home.',
                healthStatus: { vaccinated: true, neutered: true, microchipped: true, notes: 'Healthy & neutered.' },
                listingType: 'adoption',
                status: 'available',
                price: 0,
                location: { city: 'Bengaluru', state: 'Karnataka', country: 'India' },
                images: [{ ...cat3, isPrimary: true }],
                tags: ['Grey Cat', 'Quiet', 'Chubby Cheeks'],
                contactInfo: { phone: '+919765432109', email: 'ananya.patel@example.com', preferredMethod: 'email' },
                isFeatured: true,
                isVerified: true,
                viewCount: 145,
            },
            {
                owner: priya._id,
                name: 'Simba',
                species: 'cat',
                breed: 'Maine Coon',
                age: { value: 1.5, unit: 'years' },
                gender: 'male',
                size: 'large',
                color: 'Orange Tabby',
                description: 'Gentle giant Maine Coon cat. Very social and friendly.',
                healthStatus: { vaccinated: true, neutered: true, microchipped: true, notes: 'Regular checkups.' },
                listingType: 'rehoming',
                status: 'available',
                price: 0,
                location: { city: 'Hyderabad', state: 'Telangana', country: 'India' },
                images: [{ ...cat4, isPrimary: true }],
                tags: ['Big Cat', 'Friendly', 'Maine Coon'],
                contactInfo: { phone: '+919812345678', email: 'priya.sharma@example.com', preferredMethod: 'phone' },
                isFeatured: false,
                isVerified: true,
                viewCount: 160,
            },
            {
                owner: ananya._id,
                name: 'Chloe',
                species: 'cat',
                breed: 'Scottish Fold',
                age: { value: 8, unit: 'months' },
                gender: 'female',
                size: 'small',
                color: 'Silver',
                description: 'Adorable Scottish Fold kitten with cute folded ears.',
                healthStatus: { vaccinated: true, neutered: false, microchipped: false, notes: 'Vaccinated.' },
                listingType: 'sale',
                status: 'available',
                price: 15000,
                location: { city: 'Kolkata', state: 'West Bengal', country: 'India' },
                images: [{ ...cat5, isPrimary: true }],
                tags: ['Folded Ears', 'Silver', 'Cute'],
                contactInfo: { phone: '+919765432109', email: 'ananya.patel@example.com', preferredMethod: 'email' },
                isFeatured: false,
                isVerified: true,
                viewCount: 104,
            },

            // ── 🦜 BIRDS (5) ──
            {
                owner: priya._id,
                name: 'Rio',
                species: 'bird',
                breed: 'Blue & Gold Macaw',
                age: { value: 2, unit: 'years' },
                gender: 'male',
                size: 'large',
                color: 'Blue & Yellow',
                description: 'Intelligent Macaw parrot. Speaks several words and loves human interaction.',
                healthStatus: { vaccinated: true, neutered: false, microchipped: true, notes: 'Avian vet approved.' },
                listingType: 'sale',
                status: 'available',
                price: 25000,
                location: { city: 'Delhi', state: 'Delhi', country: 'India' },
                images: [{ ...bird1, isPrimary: true }],
                tags: ['Talking Bird', 'Macaw', 'Smart'],
                contactInfo: { phone: '+919812345678', email: 'priya.sharma@example.com', preferredMethod: 'phone' },
                isFeatured: true,
                isVerified: true,
                viewCount: 195,
            },
            {
                owner: rahul._id,
                name: 'Kiwi',
                species: 'bird',
                breed: 'Cockatiel',
                age: { value: 1, unit: 'years' },
                gender: 'female',
                size: 'small',
                color: 'Grey & Yellow',
                description: 'Sweet Cockatiel bird. Whistles tunes and loves sitting on shoulders.',
                healthStatus: { vaccinated: true, neutered: false, microchipped: false, notes: 'Healthy plumage.' },
                listingType: 'adoption',
                status: 'available',
                price: 0,
                location: { city: 'Mumbai', state: 'Maharashtra', country: 'India' },
                images: [{ ...bird2, isPrimary: true }],
                tags: ['Whistling', 'Tame', 'Cockatiel'],
                contactInfo: { phone: '+919898765432', email: 'rahul.verma@example.com', preferredMethod: 'platform' },
                isFeatured: false,
                isVerified: true,
                viewCount: 88,
            },
            {
                owner: ananya._id,
                name: 'Sunny',
                species: 'bird',
                breed: 'Budgerigar (Lovebird)',
                age: { value: 5, unit: 'months' },
                gender: 'male',
                size: 'small',
                color: 'Yellow & Green',
                description: 'Cheerful pair of Lovebirds looking for a caring home with big cage.',
                healthStatus: { vaccinated: true, neutered: false, microchipped: false, notes: 'Active & singing.' },
                listingType: 'adoption',
                status: 'available',
                price: 0,
                location: { city: 'Bengaluru', state: 'Karnataka', country: 'India' },
                images: [{ ...bird3, isPrimary: true }],
                tags: ['Lovebird', 'Budgie', 'Singing'],
                contactInfo: { phone: '+919765432109', email: 'ananya.patel@example.com', preferredMethod: 'email' },
                isFeatured: false,
                isVerified: true,
                viewCount: 72,
            },
            {
                owner: rahul._id,
                name: 'Charlie',
                species: 'bird',
                breed: 'African Grey Parrot',
                age: { value: 3, unit: 'years' },
                gender: 'male',
                size: 'medium',
                color: 'Grey & Red Tail',
                description: 'Highly articulate African Grey parrot with extensive vocabulary.',
                healthStatus: { vaccinated: true, neutered: false, microchipped: true, notes: 'Vet checked.' },
                listingType: 'rehoming',
                status: 'available',
                price: 0,
                location: { city: 'Chennai', state: 'Tamil Nadu', country: 'India' },
                images: [{ ...bird4, isPrimary: true }],
                tags: ['African Grey', 'Intelligent', 'Talking'],
                contactInfo: { phone: '+919898765432', email: 'rahul.verma@example.com', preferredMethod: 'phone' },
                isFeatured: true,
                isVerified: true,
                viewCount: 230,
            },
            {
                owner: priya._id,
                name: 'Peaches',
                species: 'bird',
                breed: 'Sun Conure',
                age: { value: 10, unit: 'months' },
                gender: 'female',
                size: 'medium',
                color: 'Bright Orange & Green',
                description: 'Vibrant Sun Conure parrot with energetic personality.',
                healthStatus: { vaccinated: true, neutered: false, microchipped: false, notes: 'Healthy.' },
                listingType: 'sale',
                status: 'available',
                price: 18000,
                location: { city: 'Jaipur', state: 'Rajasthan', country: 'India' },
                images: [{ ...bird5, isPrimary: true }],
                tags: ['Sun Conure', 'Colorful', 'Playful'],
                contactInfo: { phone: '+919812345678', email: 'priya.sharma@example.com', preferredMethod: 'phone' },
                isFeatured: false,
                isVerified: true,
                viewCount: 110,
            },

            // ── 🐠 FISH (5) ──
            {
                owner: priya._id,
                name: 'Goldie',
                species: 'fish',
                breed: 'Oranda Goldfish',
                age: { value: 6, unit: 'months' },
                gender: 'unknown',
                size: 'small',
                color: 'Red & White',
                description: 'Healthy Oranda Goldfish for aquarium lovers. Thrives in cold water tank.',
                healthStatus: { vaccinated: false, neutered: false, microchipped: false, notes: 'Active swimmer.' },
                listingType: 'adoption',
                status: 'available',
                price: 0,
                location: { city: 'Delhi', state: 'Delhi', country: 'India' },
                images: [{ ...fish1, isPrimary: true }],
                tags: ['Goldfish', 'Aquarium', 'Freshwater'],
                contactInfo: { phone: '+919812345678', email: 'priya.sharma@example.com', preferredMethod: 'email' },
                isFeatured: false,
                isVerified: true,
                viewCount: 65,
            },
            {
                owner: rahul._id,
                name: 'Bluey',
                species: 'fish',
                breed: 'Crown Tail Betta',
                age: { value: 4, unit: 'months' },
                gender: 'male',
                size: 'small',
                color: 'Royal Blue',
                description: 'Stunning royal blue Betta fish with crown tail fins.',
                healthStatus: { vaccinated: false, neutered: false, microchipped: false, notes: 'Healthy.' },
                listingType: 'adoption',
                status: 'available',
                price: 0,
                location: { city: 'Mumbai', state: 'Maharashtra', country: 'India' },
                images: [{ ...fish2, isPrimary: true }],
                tags: ['Betta Fish', 'Royal Blue', 'Small Tank'],
                contactInfo: { phone: '+919898765432', email: 'rahul.verma@example.com', preferredMethod: 'platform' },
                isFeatured: true,
                isVerified: true,
                viewCount: 92,
            },
            {
                owner: ananya._id,
                name: 'Nemo',
                species: 'fish',
                breed: 'Clownfish (Marine)',
                age: { value: 8, unit: 'months' },
                gender: 'male',
                size: 'small',
                color: 'Orange & White Stripes',
                description: 'Saltwater Clownfish ideal for marine reef tanks.',
                healthStatus: { vaccinated: false, neutered: false, microchipped: false, notes: 'Reef safe.' },
                listingType: 'sale',
                status: 'available',
                price: 3500,
                location: { city: 'Goa', state: 'Goa', country: 'India' },
                images: [{ ...fish3, isPrimary: true }],
                tags: ['Clownfish', 'Marine Tank', 'Saltwater'],
                contactInfo: { phone: '+919765432109', email: 'ananya.patel@example.com', preferredMethod: 'email' },
                isFeatured: false,
                isVerified: true,
                viewCount: 140,
            },
            {
                owner: rahul._id,
                name: 'Discus King',
                species: 'fish',
                breed: 'Red Turquoise Discus',
                age: { value: 1, unit: 'years' },
                gender: 'male',
                size: 'medium',
                color: 'Red & Turquoise Pattern',
                description: 'Premium show quality Discus fish with brilliant turquoise patterns.',
                healthStatus: { vaccinated: false, neutered: false, microchipped: false, notes: 'Planted tank raised.' },
                listingType: 'sale',
                status: 'available',
                price: 4200,
                location: { city: 'Kolkata', state: 'West Bengal', country: 'India' },
                images: [{ ...fish4, isPrimary: true }],
                tags: ['Discus', 'Tropical Fish', 'Show Quality'],
                contactInfo: { phone: '+919898765432', email: 'rahul.verma@example.com', preferredMethod: 'phone' },
                isFeatured: true,
                isVerified: true,
                viewCount: 180,
            },
            {
                owner: priya._id,
                name: 'Angel',
                species: 'fish',
                breed: 'Freshwater Angelfish',
                age: { value: 7, unit: 'months' },
                gender: 'female',
                size: 'medium',
                color: 'Silver & Black Stripes',
                description: 'Majestic Freshwater Angelfish pair for community aquariums.',
                healthStatus: { vaccinated: false, neutered: false, microchipped: false, notes: 'Healthy.' },
                listingType: 'adoption',
                status: 'available',
                price: 0,
                location: { city: 'Ahmedabad', state: 'Gujarat', country: 'India' },
                images: [{ ...fish5, isPrimary: true }],
                tags: ['Angelfish', 'Freshwater', 'Community Tank'],
                contactInfo: { phone: '+919812345678', email: 'priya.sharma@example.com', preferredMethod: 'email' },
                isFeatured: false,
                isVerified: true,
                viewCount: 78,
            },

            // ── 🐰 RABBITS (5) ──
            {
                owner: priya._id,
                name: 'Coco',
                species: 'rabbit',
                breed: 'Holland Lop',
                age: { value: 8, unit: 'months' },
                gender: 'female',
                size: 'small',
                color: 'Brown',
                description: 'Adorable Holland Lop bunny looking for a warm home. Litter trained.',
                healthStatus: { vaccinated: true, neutered: true, microchipped: false, notes: 'Vet checked.' },
                listingType: 'adoption',
                status: 'available',
                price: 0,
                location: { city: 'Delhi', state: 'Delhi', country: 'India' },
                images: [{ ...rabbit1, isPrimary: true }],
                tags: ['Cute', 'Bunny', 'Gentle'],
                contactInfo: { phone: '+919812345678', email: 'priya.sharma@example.com', preferredMethod: 'email' },
                isFeatured: false,
                isVerified: true,
                viewCount: 90,
            },
            {
                owner: ananya._id,
                name: 'Snowball',
                species: 'rabbit',
                breed: 'Netherland Dwarf',
                age: { value: 6, unit: 'months' },
                gender: 'male',
                size: 'small',
                color: 'Pure White',
                description: 'Tiny Netherland Dwarf rabbit with soft white fur and ruby eyes.',
                healthStatus: { vaccinated: true, neutered: false, microchipped: false, notes: 'Vaccinated.' },
                listingType: 'sale',
                status: 'available',
                price: 3000,
                location: { city: 'Bengaluru', state: 'Karnataka', country: 'India' },
                images: [{ ...rabbit2, isPrimary: true }],
                tags: ['Dwarf Bunny', 'White', 'Tiny'],
                contactInfo: { phone: '+919765432109', email: 'ananya.patel@example.com', preferredMethod: 'phone' },
                isFeatured: true,
                isVerified: true,
                viewCount: 135,
            },
            {
                owner: rahul._id,
                name: 'Bunbun',
                species: 'rabbit',
                breed: 'Lionhead Rabbit',
                age: { value: 1, unit: 'years' },
                gender: 'female',
                size: 'small',
                color: 'Cream & Grey',
                description: 'Fluffy Lionhead rabbit with a cute mane around head.',
                healthStatus: { vaccinated: true, neutered: true, microchipped: false, notes: 'Spayed.' },
                listingType: 'adoption',
                status: 'available',
                price: 0,
                location: { city: 'Mumbai', state: 'Maharashtra', country: 'India' },
                images: [{ ...rabbit3, isPrimary: true }],
                tags: ['Lionhead', 'Fluffy', 'Friendly'],
                contactInfo: { phone: '+919898765432', email: 'rahul.verma@example.com', preferredMethod: 'platform' },
                isFeatured: false,
                isVerified: true,
                viewCount: 82,
            },
            {
                owner: priya._id,
                name: 'Oreo',
                species: 'rabbit',
                breed: 'Mini Rex',
                age: { value: 5, unit: 'months' },
                gender: 'male',
                size: 'small',
                color: 'Black & White Spot',
                description: 'Velvety smooth Mini Rex rabbit. Very playful and affectionate.',
                healthStatus: { vaccinated: true, neutered: false, microchipped: false, notes: 'Dewormed.' },
                listingType: 'adoption',
                status: 'available',
                price: 0,
                location: { city: 'Pune', state: 'Maharashtra', country: 'India' },
                images: [{ ...rabbit4, isPrimary: true }],
                tags: ['Velvet Fur', 'Mini Rex', 'Playful'],
                contactInfo: { phone: '+919812345678', email: 'priya.sharma@example.com', preferredMethod: 'phone' },
                isFeatured: false,
                isVerified: true,
                viewCount: 75,
            },
            {
                owner: ananya._id,
                name: 'Hazel',
                species: 'rabbit',
                breed: 'Flemish Giant',
                age: { value: 1.5, unit: 'years' },
                gender: 'female',
                size: 'large',
                color: 'Fawn',
                description: 'Gentle giant Flemish Giant rabbit. Super calm and loves head scratches.',
                healthStatus: { vaccinated: true, neutered: true, microchipped: true, notes: 'Health checked.' },
                listingType: 'rehoming',
                status: 'available',
                price: 0,
                location: { city: 'Lucknow', state: 'Uttar Pradesh', country: 'India' },
                images: [{ ...rabbit5, isPrimary: true }],
                tags: ['Big Rabbit', 'Gentle Giant', 'Calm'],
                contactInfo: { phone: '+919765432109', email: 'ananya.patel@example.com', preferredMethod: 'email' },
                isFeatured: true,
                isVerified: true,
                viewCount: 160,
            },

            // ── 🐹 HAMSTERS (5 - Owned by Raj Dubey) ──
            {
                owner: raj._id,
                name: 'Peanut',
                species: 'hamster',
                breed: 'Syrian Hamster',
                age: { value: 4, unit: 'months' },
                gender: 'male',
                size: 'small',
                color: 'Golden Orange',
                description: 'Adorable Syrian Hamster. Energetic, loves running on wheel and eating sunflower seeds.',
                healthStatus: { vaccinated: false, neutered: false, microchipped: false, notes: 'Vet checked & healthy.' },
                listingType: 'adoption',
                status: 'available',
                price: 0,
                location: { city: 'Noida', state: 'Uttar Pradesh', country: 'India' },
                images: [{ ...hamster1, isPrimary: true }],
                tags: ['Hamster', 'Syrian', 'Cute'],
                contactInfo: { phone: '+919988776655', email: 'raj.dubey@example.com', preferredMethod: 'phone' },
                isFeatured: true,
                isVerified: true,
                viewCount: 125,
            },
            {
                owner: raj._id,
                name: 'Nibbles',
                species: 'hamster',
                breed: 'Dwarf Campbell Hamster',
                age: { value: 3, unit: 'months' },
                gender: 'female',
                size: 'small',
                color: 'Grey & White Stripe',
                description: 'Tiny Dwarf Campbell hamster. Very curious and loves burrowing in bedding.',
                healthStatus: { vaccinated: false, neutered: false, microchipped: false, notes: 'Dewormed.' },
                listingType: 'adoption',
                status: 'available',
                price: 0,
                location: { city: 'Delhi', state: 'Delhi', country: 'India' },
                images: [{ ...hamster2, isPrimary: true }],
                tags: ['Dwarf Hamster', 'Tiny', 'Playful'],
                contactInfo: { phone: '+919988776655', email: 'raj.dubey@example.com', preferredMethod: 'phone' },
                isFeatured: false,
                isVerified: true,
                viewCount: 98,
            },
            {
                owner: raj._id,
                name: 'Cheeks',
                species: 'hamster',
                breed: 'Roborovski Hamster',
                age: { value: 5, unit: 'months' },
                gender: 'male',
                size: 'small',
                color: 'Sandy Brown',
                description: 'Super fast Roborovski hamster with adorable cheek pouches.',
                healthStatus: { vaccinated: false, neutered: false, microchipped: false, notes: 'Healthy & active.' },
                listingType: 'sale',
                status: 'available',
                price: 1200,
                location: { city: 'Gurugram', state: 'Haryana', country: 'India' },
                images: [{ ...hamster3, isPrimary: true }],
                tags: ['Robo Hamster', 'Fast', 'Adorable'],
                contactInfo: { phone: '+919988776655', email: 'raj.dubey@example.com', preferredMethod: 'phone' },
                isFeatured: false,
                isVerified: true,
                viewCount: 140,
            },
            {
                owner: raj._id,
                name: 'Mochi',
                species: 'hamster',
                breed: 'Winter White Dwarf',
                age: { value: 6, unit: 'months' },
                gender: 'female',
                size: 'small',
                color: 'White Pearl',
                description: 'Winter White Dwarf hamster. Soft coat that turns lighter in winter.',
                healthStatus: { vaccinated: false, neutered: false, microchipped: false, notes: 'Vet checked.' },
                listingType: 'adoption',
                status: 'available',
                price: 0,
                location: { city: 'Noida', state: 'Uttar Pradesh', country: 'India' },
                images: [{ ...hamster4, isPrimary: true }],
                tags: ['Winter White', 'Soft Coat', 'Tame'],
                contactInfo: { phone: '+919988776655', email: 'raj.dubey@example.com', preferredMethod: 'email' },
                isFeatured: true,
                isVerified: true,
                viewCount: 110,
            },
            {
                owner: raj._id,
                name: 'Pippin',
                species: 'hamster',
                breed: 'Chinese Hamster',
                age: { value: 4, unit: 'months' },
                gender: 'male',
                size: 'small',
                color: 'Brown Stripe',
                description: 'Gentle Chinese hamster with slender body and friendly demeanor.',
                healthStatus: { vaccinated: false, neutered: false, microchipped: false, notes: 'Healthy.' },
                listingType: 'sale',
                status: 'available',
                price: 1500,
                location: { city: 'Ghaziabad', state: 'Uttar Pradesh', country: 'India' },
                images: [{ ...hamster5, isPrimary: true }],
                tags: ['Chinese Hamster', 'Gentle', 'Cute'],
                contactInfo: { phone: '+919988776655', email: 'raj.dubey@example.com', preferredMethod: 'phone' },
                isFeatured: false,
                isVerified: true,
                viewCount: 85,
            },

            // ── 🦎 REPTILES (5 - Owned by Raj Dubey) ──
            {
                owner: raj._id,
                name: 'Spike',
                species: 'reptile',
                breed: 'Bearded Dragon',
                age: { value: 1.5, unit: 'years' },
                gender: 'male',
                size: 'medium',
                color: 'Yellowish Tan',
                description: 'Tame Bearded Dragon lizard. Eats greens & crickets well, loves basking.',
                healthStatus: { vaccinated: false, neutered: false, microchipped: false, notes: 'Reptile vet checked.' },
                listingType: 'rehoming',
                status: 'available',
                price: 0,
                location: { city: 'Noida', state: 'Uttar Pradesh', country: 'India' },
                images: [{ ...reptile1, isPrimary: true }],
                tags: ['Bearded Dragon', 'Reptile', 'Tame'],
                contactInfo: { phone: '+919988776655', email: 'raj.dubey@example.com', preferredMethod: 'phone' },
                isFeatured: true,
                isVerified: true,
                viewCount: 210,
            },
            {
                owner: raj._id,
                name: 'Ziggy',
                species: 'reptile',
                breed: 'Leopard Gecko',
                age: { value: 1, unit: 'years' },
                gender: 'female',
                size: 'small',
                color: 'Yellow & Black Spots',
                description: 'Docile Leopard Gecko with beautiful spotted pattern. Comes with terrarium setup.',
                healthStatus: { vaccinated: false, neutered: false, microchipped: false, notes: 'Regenerated fat tail.' },
                listingType: 'sale',
                status: 'available',
                price: 4500,
                location: { city: 'Delhi', state: 'Delhi', country: 'India' },
                images: [{ ...reptile2, isPrimary: true }],
                tags: ['Leopard Gecko', 'Docile', 'Spot Pattern'],
                contactInfo: { phone: '+919988776655', email: 'raj.dubey@example.com', preferredMethod: 'phone' },
                isFeatured: false,
                isVerified: true,
                viewCount: 165,
            },
            {
                owner: raj._id,
                name: 'Shelly',
                species: 'reptile',
                breed: 'Red-Eared Slider Turtle',
                age: { value: 2, unit: 'years' },
                gender: 'female',
                size: 'small',
                color: 'Green Shell',
                description: 'Healthy Red-Eared Slider aquatic turtle with basking lamp and filter.',
                healthStatus: { vaccinated: false, neutered: false, microchipped: false, notes: 'Healthy shell.' },
                listingType: 'adoption',
                status: 'available',
                price: 0,
                location: { city: 'Noida', state: 'Uttar Pradesh', country: 'India' },
                images: [{ ...reptile3, isPrimary: true }],
                tags: ['Turtle', 'Aquatic Pet', 'Easy Care'],
                contactInfo: { phone: '+919988776655', email: 'raj.dubey@example.com', preferredMethod: 'email' },
                isFeatured: false,
                isVerified: true,
                viewCount: 130,
            },
            {
                owner: raj._id,
                name: 'Draco',
                species: 'reptile',
                breed: 'Green Iguana',
                age: { value: 2, unit: 'years' },
                gender: 'male',
                size: 'large',
                color: 'Vibrant Green',
                description: 'Impressive Green Iguana. Requires spacious enclosure and proper UVB lighting.',
                healthStatus: { vaccinated: false, neutered: false, microchipped: false, notes: 'Active herbivore.' },
                listingType: 'rehoming',
                status: 'available',
                price: 0,
                location: { city: 'Gurugram', state: 'Haryana', country: 'India' },
                images: [{ ...reptile4, isPrimary: true }],
                tags: ['Iguana', 'Green Reptile', 'Exotic'],
                contactInfo: { phone: '+919988776655', email: 'raj.dubey@example.com', preferredMethod: 'phone' },
                isFeatured: true,
                isVerified: true,
                viewCount: 240,
            },
            {
                owner: raj._id,
                name: 'Kaa',
                species: 'reptile',
                breed: 'Ball Python',
                age: { value: 1.5, unit: 'years' },
                gender: 'male',
                size: 'medium',
                color: 'Classic Morph',
                description: 'Calm and docile Ball Python snake. Feeds regularly on frozen/thawed prey.',
                healthStatus: { vaccinated: false, neutered: false, microchipped: false, notes: 'Shedding complete.' },
                listingType: 'sale',
                status: 'available',
                price: 8000,
                location: { city: 'Faridabad', state: 'Haryana', country: 'India' },
                images: [{ ...reptile5, isPrimary: true }],
                tags: ['Ball Python', 'Snake', 'Docile'],
                contactInfo: { phone: '+919988776655', email: 'raj.dubey@example.com', preferredMethod: 'phone' },
                isFeatured: false,
                isVerified: true,
                viewCount: 190,
            },

            // ── 🐾 OTHER PETS (5) ──
            {
                owner: priya._id,
                name: 'Gizmo',
                species: 'other',
                breed: 'Abyssinian Guinea Pig',
                age: { value: 6, unit: 'months' },
                gender: 'male',
                size: 'small',
                color: 'Tricolor Rosettes',
                description: 'Adorable vocal Guinea Pig with cute rosette fur pattern.',
                healthStatus: { vaccinated: false, neutered: false, microchipped: false, notes: 'Vet checked.' },
                listingType: 'adoption',
                status: 'available',
                price: 0,
                location: { city: 'Hyderabad', state: 'Telangana', country: 'India' },
                images: [{ ...other1, isPrimary: true }],
                tags: ['Guinea Pig', 'Cavy', 'Vocal'],
                contactInfo: { phone: '+919812345678', email: 'priya.sharma@example.com', preferredMethod: 'email' },
                isFeatured: false,
                isVerified: true,
                viewCount: 110,
            },
            {
                owner: rahul._id,
                name: 'Bandit',
                species: 'other',
                breed: 'Sable Ferret',
                age: { value: 1, unit: 'years' },
                gender: 'male',
                size: 'small',
                color: 'Sable Mask',
                description: 'Playful and curious Sable Ferret. Litter trained and neutered.',
                healthStatus: { vaccinated: true, neutered: true, microchipped: true, notes: 'Ferret vaccinated.' },
                listingType: 'sale',
                status: 'available',
                price: 6000,
                location: { city: 'Chandigarh', state: 'Punjab', country: 'India' },
                images: [{ ...other2, isPrimary: true }],
                tags: ['Ferret', 'Playful', 'Sable'],
                contactInfo: { phone: '+919898765432', email: 'rahul.verma@example.com', preferredMethod: 'phone' },
                isFeatured: true,
                isVerified: true,
                viewCount: 205,
            },
            {
                owner: ananya._id,
                name: 'Charlie',
                species: 'other',
                breed: 'Chinchilla',
                age: { value: 1, unit: 'years' },
                gender: 'male',
                size: 'small',
                color: 'Standard Grey',
                description: 'Soft Chinchilla with dust bath house and cage included.',
                healthStatus: { vaccinated: false, neutered: false, microchipped: false, notes: 'Healthy fur.' },
                listingType: 'adoption',
                status: 'available',
                price: 0,
                location: { city: 'Bengaluru', state: 'Karnataka', country: 'India' },
                images: [{ ...other3, isPrimary: true }],
                tags: ['Chinchilla', 'Soft Fur', 'Exotic'],
                contactInfo: { phone: '+919765432109', email: 'ananya.patel@example.com', preferredMethod: 'email' },
                isFeatured: false,
                isVerified: true,
                viewCount: 115,
            },
            {
                owner: priya._id,
                name: 'Sammy',
                species: 'other',
                breed: 'Sugar Glider',
                age: { value: 8, unit: 'months' },
                gender: 'male',
                size: 'small',
                color: 'Grey & Black Stripe',
                description: 'Social Sugar Glider pair. Glides onto hands and loves fruit treats.',
                healthStatus: { vaccinated: false, neutered: false, microchipped: false, notes: 'Vet checked.' },
                listingType: 'rehoming',
                status: 'available',
                price: 0,
                location: { city: 'Delhi', state: 'Delhi', country: 'India' },
                images: [{ ...other4, isPrimary: true }],
                tags: ['Sugar Glider', 'Glider', 'Pocket Pet'],
                contactInfo: { phone: '+919812345678', email: 'priya.sharma@example.com', preferredMethod: 'phone' },
                isFeatured: false,
                isVerified: true,
                viewCount: 150,
            },
            {
                owner: rahul._id,
                name: 'Rusty',
                species: 'other',
                breed: 'Hedgehog',
                age: { value: 9, unit: 'months' },
                gender: 'male',
                size: 'small',
                color: 'Salt & Pepper',
                description: 'Adorable African Pygmy Hedgehog. Cute quills and friendly nocturnal pet.',
                healthStatus: { vaccinated: false, neutered: false, microchipped: false, notes: 'Healthy.' },
                listingType: 'sale',
                status: 'available',
                price: 5000,
                location: { city: 'Mumbai', state: 'Maharashtra', country: 'India' },
                images: [{ ...other5, isPrimary: true }],
                tags: ['Hedgehog', 'Quills', 'Cute'],
                contactInfo: { phone: '+919898765432', email: 'rahul.verma@example.com', preferredMethod: 'platform' },
                isFeatured: true,
                isVerified: true,
                viewCount: 190,
            },
        ];

        const pets = await Pet.create(petsData);
        console.log(`✅ ${pets.length} Total Pets (including 5 Hamsters & 5 Reptiles owned by Raj Dubey) Created in MongoDB Atlas.`);

        // ── 4. Create Saved Pets ──
        console.log('🔖 Seeding Saved Pets...');
        await SavedPet.create([
            { user: rahul._id, pet: pets[0]._id },
            { user: raj._id, pet: pets[5]._id },
            { user: priya._id, pet: pets[25]._id },
            { user: ananya._id, pet: pets[30]._id },
        ]);
        console.log('✅ Saved Pets seeded.');

        // ── 5. Create Reports ──
        console.log('🚩 Seeding Moderation Reports...');
        await Report.create([
            {
                reporter: ananya._id,
                pet: pets[3]._id,
                targetType: 'pet',
                reason: 'misleading_information',
                description: 'The price mentioned seems slightly different from what owner stated in chat.',
                status: 'pending',
            },
            {
                reporter: raj._id,
                pet: pets[0]._id,
                targetType: 'pet',
                reason: 'spam',
                description: 'Multiple duplicate entries posted.',
                status: 'pending',
            },
            {
                reporter: ananya._id,
                reportedUser: rahul._id,
                targetType: 'user',
                reason: 'inappropriate_content',
                description: 'Unresponsive communication and suspicious profile details.',
                status: 'pending',
            },
        ]);
        console.log('✅ Reports seeded.');

        console.log('\n===================================================================');
        console.log('✨ ALL CATEGORIES (DOG, CAT, BIRD, FISH, RABBIT, HAMSTER, REPTILE, OTHER) ✨');
        console.log('✨ 40 PETS TOTAL SEEDED WITH RAJ DUBEY USER TO CLOUDINARY & MONGO ATLAS! ✨');
        console.log('===================================================================');
        process.exit(0);
    } catch (error) {
        console.error('❌ Error during seeding:', error);
        process.exit(1);
    }
};

seedData();
